#!/usr/bin/osascript

# This is an applescript that returns the label of the recording button for Nicecast
# It either echos "Start Recodring" if Nicecast is not recording, or "Stop Recording" if nicecast is 

tell application "System Events"
	tell process "Nicecast"
		set xxx to name of every menu item of menu 1 of menu bar item "Control" of menu bar 1
		do shell script "echo " & (item 4 of xxx)
	end tell
end tell



