#!/usr/bin/osascript


tell application "System Events"
	tell process "Nicecast"
		set xxx to name of every menu item of menu 1 of menu bar item "Control" of menu bar 1
		do shell script "echo " & (item 4 of xxx)
	end tell
end tell



